services:
  - type: web
    name: backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    postDeploy: bin/rails db:seed RAILS_ENV=production
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend-db
          property: connectionString
      - key: REDIS_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: backend-db
    plan: free
